version: '2'

services:
  
  test-build-container:
    container_name: test-build-container
    build:
      context: .
      dockerfile: Dockerfile-test
    image: ${REGISTRY_IMAGE}/${COMMIT_REF}:build_local_cache-${COMMIT_SHA}

  upload-container:
    container_name: upload-container
    build:
      context: .
      args:
        AUTH_LOGIN: ${CONAN_LOGIN}
        AUTH_PASS: ${CONAN_PASSWORD}
        BUILD_LOCAL_CACHE_IMAGE: ${REGISTRY_IMAGE}/${COMMIT_REF}:build_local_cache-${COMMIT_SHA}
      dockerfile: Dockerfile-update
    depends_on:
      - test-build-container
