FROM ubuntu:jammy-20230301 as build_local_cache
ENV TZ=America/US

RUN \
    apt update  \
    && apt upgrade -y \
    && apt install -y \
        software-properties-common \
        python3-dev \
        python3-pip\
        pkg-config\
    && apt clean \
    && rm -rf /var/lib/apt/lists/* \
    && pip3 install --no-cache-dir conan==1.60 cmake==3.21.0

RUN conan profile detect \
    && conan remote add conan_streamlabs_20 http://artartifactory.streamlabs:8082/artifactory/api/conan/conan_streamlabs_20 --index 0

WORKDIR /src


COPY ./src/recipes-create.sh ./recipes-create.sh
COPY ./recipes ./recipes
COPY ./src/req-seq.txt ./req-seq.txt
RUN chmod 777 recipes-create.sh

ARG CACHEBUST
RUN echo ${CACHEBUST}
RUN ./recipes-create.sh
