versions:
  "1.0.0a12":
    folder: "all"
  "1.0.0a11":
    folder: "all"
  "1.0.0a10":
    folder: "all"
  "1.0.0a9":
    folder: "all"
  "1.0.0a8":
    folder: "all"
  "1.0.0a7":
    folder: "all"
  "1.0.0a4":
    folder: "all"
