FROM ubuntu:18.04

RUN apt update && \
    apt upgrade -y && \
    apt install -y curl gnupg apt-transport-https && \
    curl -fsSL https://bazel.build/bazel-release.pub.gpg | apt-key add && \
    echo 'deb https://storage.googleapis.com/bazel-apt stable jdk1.8' | tee /etc/apt/sources.list.d/bazel.list && \
    apt update && \
    apt install -y gcc g++ bazel bazel-5.0.0 python3-pip git && \
    rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/* && \
    pip3 install --no-cache-dir --user conan

RUN git clone https://github.com/duckstax/conan-duckstax.git

ENV HOME="/root"
ENV PATH="$PATH:$HOME/.local/bin"

RUN export && \
    cd conan-duckstax/recipes/proxy-wasm-cpp-host/all && \
    conan profile new default --detect --force && \
    conan profile update settings.compiler.libcxx=libstdc++11 default && \
    conan create . 3c703dcc44e7fc24062215e4f3c5c16d616362e8@duckstax/stable

RUN  conan remote add duckstax http://conan.duckstax.com:9300  && \
     conan user xxx -r duckstax -p xxx && \
     conan upload  proxy-wasm-cpp-host/3c703dcc44e7fc24062215e4f3c5c16d616362e8@duckstax/stable -r duckstax --all


