#on: [push, pull_request]
on: [push]

jobs:
  build:
    strategy:
      matrix:
        configuration: [
          {"UBUNTU_VERSION":"18.04"},
          {"UBUNTU_VERSION":"20.04"},
          {"UBUNTU_VERSION":"22.04"},
        ]

    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{matrix.configuration.UBUNTU_VERSION}}

    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update && apt-get install -y \
            software-properties-common ca-certificates \
            ninja-build make \
            zlib1g-dev wget

          python3 -m pip install --upgrade pip
          python3 -m pip install --no-cache-dir conan==1.60 cmake

      - name: recipes-create
        run: |
          ./recipes-create.sh

      - name: update-remote
        run: |
          ./update-remote.sh
